version: '3'
services:
  rails:
    build: .
    ports:
      - 3000:3000
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    volumes:
      - ..:/Projects/ryu-sato/bc-employee-mgmt
